### ISSUE TITLE
UI/UX Improvement

### ISSUE THREAD

**Issue by d-code-h** [d-code-h/task-management-app#3]

**Comment by mahendra3399** [comment]
Hello @d-code-h, 
I will start by reviewing the current state of the UI/UX to identify areas for improvement
If available, I will look at any existing feedback or suggestions from users or contributors
I will make the necessary changes to improve the UI/UX, ensuring that the design is both functional and visually appealing
I will thoroughly test the changes to ensure they work seamlessly across different devices and browsers.

Kindly assign me this issue Under Hacktoberfest 2024

**Comment by d-code-h** [comment]
Hello @mahendra3399 ,

Thank you so much for your willingness to contribute and help with the UI/UX improvement in the Vite-based task management project! I truly appreciate your offer to enhance the design.

I wanted to inform you that I have decided to migrate the project to **Next.js** for better flexibility, scalability, and future integration needs. The new repository now has 'Acceptance Criteria' expected on each issue, and I believe this new structure will provide a smoother experience working on the project.

**While this Vite repo will soon be closed down**, I would love to invite you to contribute to the new Next.js repository, where you can continue the great work you’ve started. I'am sure your UI/UX expertise will be a valuable addition, and the same issue is available for you to tackle, now under **Hacktoberfest 2024**.

Please feel free to check out the new repo here: [https://github.com/d-code-h/task-management-next-app/].

I look forward to your contributions and can’t wait to see what you bring to the project. Apologies for any inconvenience caused by the migration, and thank you again for your understanding and support!

**Comment by d-code-h** [comment]
**I look forward to your contributions and can’t wait to see what you bring to the project. Apologies for any inconvenience caused by the migration, and thank you again for your understanding and support!**
